version: '3'
services:
  decidim:
    image: corp0/eparticipa-decidim:latest
    ports:
      - "4000:3000"
    volumes:
      - ./src:/code/src
      - ./scripts/init.sh:/code/init.sh
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    links:
      - pg
      - redis
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  pg-data: {}
  redis-data: {}